language: php

php:
  - '7.1'
  - '7.2'
env:
  - COMPOSER_LOWEST=0
  - COMPOSER_LOWEST=1

install:
  - '[ $COMPOSER_LOWEST == 1 ] && composer update --prefer-lowest || composer install'

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyze --level 7 src
  - ./vendor/bin/phpunit
