language: php

matrix:
  include:
    - php: '7.1'
      env: COMPOSER_LOWEST=0
    - php: '7.2'
      env: COMPOSER_LOWEST=0
    - php: '7.1'
      env: COMPOSER_LOWEST=1
    - php: '7.0'
      env: COMPOSER_LOWEST=1

install:
  - [ $COMPOSER_LOWEST == 1 ] && composer update --prefer-lowest || composer install
